spring:
  data:
    mongodb:
      database: barter-users
      host: localhost
      port: 27017
  application:
    name: user-service

logging:
  level:
    root: ERROR

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 9001