package ru.dlyubanevich.bottelegrammicroservice.stage.offerRequest.state;

public enum StateOfferRequest {

    GREETINGS_FOR_OFFER_REQUEST,
    ASK_OFFER_OPTION,
    ASK_OFFER_TYPE,
    ASK_NOMENCLATURE_NAME,
    ASK_NOMENCLATURE_OPTION,
    ASK_NOMENCLATURE_TYPE,
    ASK_NOMENCLATURE_DESCRIPTION,
    ASK_NOMENCLATURE_PHOTO,
    ASK_OFFER_DESCRIPTION,
    ASK_OFFER_REQUIREMENTS,
    SAVE_OFFER_REQUEST,
    SUCCESS_FOR_OFFER_REQUEST

}
