spring:
  data:
    mongodb:
      database: barter-telegram-bot
      host: localhost
      port: 27017
  application:
    name: bot-telegram-microservice

server:
  port: 5000

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    fetch-registry: true

webHookPath: https://10382400ec51.ngrok.io
botUserName: "@barter2021_bot"
botToken: 1788232562:AAGLUG5EeJwxbLIirZy3tJcZ6vNuN9I_uRM
