spring:
  data:
    mongodb:
      database: barter-deals
      host: localhost
      port: 27017
  application:
    name: deal-microservice

server:
  port: 9004

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    fetch-registry: true