spring:
  application:
    name: offer-processing-service

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 9006

eureka:
  client:
    fetch-registry: true