spring:
  data:
    mongodb:
      database: barter-offers
      host: localhost
      port: 27017
  application:
    name: offer-microservice

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 9002

eureka:
  client:
    fetch-registry: true