spring:
  data:
    mongodb:
      database: barter-photo
      host: localhost
      port: 27017
  application:
    name: photo-microservice

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 9006

eureka:
  client:
    fetch-registry: true

authorization: OAuth AQAAAAAF2d5UAAccbcencDF2MUq7sQBNjg07W4U
address: https://cloud-api.yandex.net/v1/disk/resources